# .github/workflows/sync.yml
name: Sync Fork

on:
  schedule:
    # 設定排程，使用 UTC 時間的 cron 語法。以下範例為每天凌晨執行一次。
    # 你可以根據需求調整，例如每六小時一次：'0 */6 * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 這個選項允許你手動觸發此 Action

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          # 使用 Personal Access Token (PAT) 而非預設的 GITHUB_TOKEN
          # 以確保可以觸發後續的 CI/CD 流程 (如果有的話)
          token: ${{ secrets.PAT }}
          # 取得所有歷史紀錄，這對於 rebase 模式很重要
          fetch-depth: 0

      - name: Sync Fork with Upstream
        uses: repo-sync/github-sync@v2
        with:
          # [必要] 原始 (上游) 專案
          source_repo: "https://github.com/nickclyde/duckduckgo-mcp-server"
          source_branch: "main"

          # [必要] 目標 (你的 fork) 專案的分支
          destination_branch: "main"

          # [可選] 你的 GitHub 使用者名稱
          github_user: "chengemnoip"

          # [必要] 傳入上面設定的 PAT
          github_token: ${{ secrets.PAT }}
